FROM btrepp/open62541:tiny
RUN apk add --no-cache make musl-dev cmake gcc gdb valgrind && rm -rf /var/cache/apk/* 
ADD . /tmp/uatools
WORKDIR /tmp/uatools/build
RUN cmake .. && \
    make && \
    make install

